version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api:
    image: node-mongo-image
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/db
    depends_on:
      - mongo

volumes:
  mongo-data:
